apiVersion: v1
kind: Service
metadata:
  name: cicd-failure-predictor
  labels:
    app: cicd-failure-predictor
spec:
  type: NodePort
  selector:
    app: cicd-failure-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
